### ISSUE TITLE
Light controller not setting up when multiprocessing

### ISSUE THREAD

**Issue by MichalLeszczynski** [MichalLeszczynski/GardenOfLife#1]
##Error message:
Traceback (most recent call last):
  File "run.py", line 53, in <module>
    pool.map(run, controllers)
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 431, in _handle_tasks
    put(task)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle SwigPyObject objects

**Comment by MichalLeszczynski** [comment]
https://docs.python.org/3.3/library/multiprocessing.html#multiprocessing-programming
